cloudbuild initial

diff --git a/cloudbuild_hcc.yaml b/cloudbuild_hcc.yaml
--- a/cloudbuild_hcc.yaml
+++ b/cloudbuild_hcc.yaml
@@ -63,7 +63,7 @@ steps:
 #   allowFailure: true
 #   waitFor: ['create a3ultra with nccl']
 
-# - id: 'create a3ultra with llama7b'
+# - id: 'create a3ultra with nemo'
 #   name: 'gcr.io/$PROJECT_ID/terraform'
 #   entrypoint: 'sh'
 #   args:
@@ -84,12 +84,12 @@ steps:
 #     -var=placement_policy_name=$_A3ULTRA_PLACEMENT_POLICY_NAME \
 #     -auto-approve -no-color
 
-#     echo "pass" > /workspace/a3u_llama7b_result.txt
+#     echo "pass" > /workspace/a3u_nemo_result.txt
 #   allowFailure: true
 #   waitFor: ["-"]
 
 
-# - id: 'cleanup a3ultra with llama7b'
+# - id: 'cleanup a3ultra with nemo'
 #   name: 'gcr.io/$PROJECT_ID/terraform'
 #   entrypoint: 'bash'
 #   args:
@@ -110,7 +110,7 @@ steps:
 #     -var=placement_policy_name=$_A3ULTRA_PLACEMENT_POLICY_NAME \
 #     -auto-approve -no-color
 #   allowFailure: true
-#   waitFor: ['create a3ultra with llama7b']
+#   waitFor: ['create a3ultra with nemo']
 
 - id: 'create a3mega with nccl'
   name: 'gcr.io/$PROJECT_ID/terraform'
@@ -133,82 +133,9 @@ steps:
     -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
     -auto-approve -no-color
 
-    echo "pass" > /workspace/a3m_nccl_result.txt
+    echo "cluster creation successfully" > /workspace/a3m_nccl_result.txt
   allowFailure: true
   waitFor: ["-"]
-
-
-- id: 'cleanup a3mega with nccl'
-  name: 'gcr.io/$PROJECT_ID/terraform'
-  entrypoint: 'bash'
-  args:
-  - '-c'
-  - |
-    set -e
-
-    cd /workspace/applications/hcc/
-    terraform destroy \
-    -var-file=a3mega_workloads.tfvars \
-    -var=project_id=$_A3MEGA_PROJECT \
-    -var=a3mega_recipe="gke-nccl" \
-    -var=gpu_type="A3 Mega" \
-    -var=node_count_gke_nccl=2 \
-    -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
-    -var=a3_mega_zone=$_A3MEGA_ZONE \
-    -var=reservation=$_A3MEGA_RESERVATION \
-    -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
-    -auto-approve -no-color
-  allowFailure: true
-  waitFor: ['check a3m NCCL result']
-
-# - id: 'create a3mega with llama7b'
-#   name: 'gcr.io/$PROJECT_ID/terraform'
-#   entrypoint: 'sh'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
-
-#     cd /workspace/applications/hcc/
-#     terraform apply \
-#     -var-file=a3mega_workloads.tfvars \
-#     -var=project_id=$_A3MEGA_PROJECT \
-#     -var=a3mega_recipe="llama3.1_7b_nemo_pretraining" \
-#     -var=gpu_type="A3 Mega" \
-#     -var=node_count_nemo=2 \
-#     -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
-#     -var=a3_ultra_zone=$_A3MEGA_ZONE \
-#     -var=reservation=$_A3MEGA_RESERVATION \
-#     -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
-#     -auto-approve -no-color
-
-#     echo "pass" > /workspace/a3m_llama7b_result.txt
-#   allowFailure: true
-#   waitFor: ["-"]
-
-
-# - id: 'cleanup a3mega with llama7b'
-#   name: 'gcr.io/$PROJECT_ID/terraform'
-#   entrypoint: 'bash'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
-
-#     cd /workspace/applications/hcc/
-#     terraform destroy \
-#     -var-file=a3mega_workloads.tfvars \
-#     -var=project_id=$_A3MEGA_PROJECT \
-#     -var=a3mega_recipe="llama3.1_7b_nemo_pretraining" \
-#     -var=gpu_type="A3 Mega" \
-#     -var=node_count_nemo=2 \
-#     -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
-#     -var=a3_ultra_zone=$_A3MEGA_ZONE \
-#     -var=reservation=$_A3MEGA_RESERVATION \
-#     -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
-#     -auto-approve -no-color
-#   allowFailure: true
-#   waitFor: ['create a3mega with llama7b']
 
 - id: 'wait for a3m nccl job to start'
   name: 'gcr.io/cloud-builders/kubectl'
@@ -234,7 +161,7 @@ steps:
         status=$(kubectl get job "$_JOB_NAME" -n default -o json | jq -r '.status.conditions[].type')
 
         if [[ "$status" == "Complete" ]]; then
-          echo "pass: nccl start successfully" > /workspace/a3m_nccl_result.txt
+          echo "nccl start successfully" > /workspace/a3m_nccl_result.txt
           exit 0
         fi
         sleep $interval
@@ -247,7 +174,7 @@ steps:
 
 - id: 'check a3m NCCL result'
   name: 'gcr.io/cloud-builders/gsutil'
-  entrypoint: 'sh'
+  entrypoint: 'bash'
   args:
   - '-c'
   - |
@@ -264,12 +191,70 @@ steps:
 
     while [ $(date +%s) -lt $(($timeout + $(date +%s))) ]; do
       if gsutil ls "$_GCS_FILE_PATH" > /dev/null 2>&1; then
-        echo "NCCL test log file(s) found matching pattern" > /workspace/a3m_nccl_result.txt
-        exit 0
+        if gsutil cat "$_GCS_FILE_PATH" | grep -q "Avg bus bandwidth"; then
+          echo "NCCL test log file(s) found with necessary contents" > /workspace/a3m_nccl_result.txt
+          exit 0
+        else
+          echo "NCCL test log file(s) found, but without 'Avg bus bandwidth'"
+          exit 1
+        fi
+      else
+        echo "Waiting for NCCL test log file(s) matching pattern: $_GCS_FILE_PATH"
+        sleep $interval
       fi
     done
+    echo "Timeout reached. NCCL test log file(s) not found or test did not complete within $timeout seconds."
     exit 1
-  waitFor: ['wait for a3m nccl job to start']
+  allowFailure: true
+  waitFor: ["wait for a3m nccl job to start"]
+
+- id: 'cleanup a3mega with nccl'
+  name: 'gcr.io/$PROJECT_ID/terraform'
+  entrypoint: 'bash'
+  args:
+  - '-c'
+  - |
+    set -e
+
+    cd /workspace/applications/hcc/
+    terraform destroy \
+    -var-file=a3mega_workloads.tfvars \
+    -var=project_id=$_A3MEGA_PROJECT \
+    -var=a3mega_recipe="gke-nccl" \
+    -var=gpu_type="A3 Mega" \
+    -var=node_count_gke_nccl=2 \
+    -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
+    -var=a3_mega_zone=$_A3MEGA_ZONE \
+    -var=reservation=$_A3MEGA_RESERVATION \
+    -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
+    -auto-approve -no-color
+  allowFailure: true
+  waitFor: ["check a3m NCCL result"]
+
+- id: 'create a3mega with nemo'
+  name: 'gcr.io/$PROJECT_ID/terraform'
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
+
+    cd /workspace/applications/hcc/
+    terraform apply \
+    -var-file=a3mega_workloads.tfvars \
+    -var=project_id=$_A3MEGA_PROJECT \
+    -var=a3mega_recipe="llama3.1_7b_nemo_pretraining" \
+    -var=gpu_type="A3 Mega" \
+    -var=node_count_nemo=2 \
+    -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
+    -var=a3_ultra_zone=$_A3MEGA_ZONE \
+    -var=reservation=$_A3MEGA_RESERVATION \
+    -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
+    -auto-approve -no-color
+
+    echo "cluster creation successfully" > /workspace/a3m_nemo_result.txt
+  allowFailure: true
+  waitFor: ["cleanup a3mega with nccl"]
 
 - id: 'wait for a3m nemo job to start'
   name: 'gcr.io/cloud-builders/kubectl'
@@ -293,7 +278,7 @@ steps:
         status=$(kubectl get job benchmark -n default -o json | jq -r '.status.conditions[].type')
 
         if [[ "$status" == "Complete" ]]; then
-          echo "pass: nccl start successfully" > /workspace/a3m_nccl_result.txt
+          echo "nemo start successfully" > /workspace/a3m_nemo_result.txt
           exit 0
         fi
         sleep $interval
@@ -302,7 +287,7 @@ steps:
     echo "Timeout reached. Job did not start within $timeout seconds."
     exit 1
   allowFailure: true
-  waitFor: ['create a3mega with llama7b']
+  waitFor: ['create a3mega with nemo']
 
 - id: 'check a3m nemo result'
   name: 'gcr.io/cloud-builders/gsutil'
@@ -314,24 +299,62 @@ steps:
 
     # Set the timeout and interval
     timeout=300  # 10 minutes
-    interval=15  # 15 seconds
+    interval=30  # 15 seconds
 
     # Construct the bucket name and file pattern
     _BUCKET_NAME="${_A3MEGA_PROJECT}-${_A3MEGA_DEPLOYMENT_NAME}-result"
-    _FILE_PATTERN="all_gather_perf*"
-    _GCS_FILE_PATH="gs://${_BUCKET_NAME}/${_FILE_PATTERN}.txt"
+    _FILE_PREFIX="nemo-experiments/benchmark-"
+    _FILE_SUFFIX="/dllogger/rank-0/dllogger.json"
+    _GCS_FILE_PATTERN="gs://${_BUCKET_NAME}/${_FILE_PREFIX}*${_FILE_SUFFIX}"
 
     while [ $(date +%s) -lt $(($timeout + $(date +%s))) ]; do
-      if gsutil ls "$_GCS_FILE_PATH" > /dev/null 2>&1; then
-        echo "NCCL test log file(s) found matching pattern" > /workspace/a3m_nccl_result.txt
-        exit 0
+      # List files matching the pattern
+      file_list=$(gsutil ls "$_GCS_FILE_PATTERN" 2> /dev/null)
+      if [ -n "$file_list" ]; then
+        # Loop through each matching file
+        for file in $file_list; do
+          # Check for the required strings in the file
+          if gsutil cat "$file" | grep -q "reduced_train_loss" && gsutil cat "$file" | grep -q "validation_step_timing"; then
+            echo "Nemo result file found with necessary contents" > /workspace/a3m_nemo_result.txt
+            exit 0
+          else
+            echo "Nemo result file found, but missing 'reduced_train_loss' or 'validation_step_timing'"
+            exit 1
+          fi
+        done
+      else
+        echo "Waiting for Nemo result file(s) matching pattern: $_GCS_FILE_PATTERN"
+        sleep $interval
       fi
     done
+
+    echo "Timeout reached. Nemo result file(s) not found or test did not complete within $timeout seconds."
     exit 1
+  allowFailure: true
   waitFor: ['wait for a3m nemo job to start']
 
+- id: 'cleanup a3mega with nemo'
+  name: 'gcr.io/$PROJECT_ID/terraform'
+  entrypoint: 'bash'
+  args:
+  - '-c'
+  - |
+    set -e
 
-
+    cd /workspace/applications/hcc/
+    terraform destroy \
+    -var-file=a3mega_workloads.tfvars \
+    -var=project_id=$_A3MEGA_PROJECT \
+    -var=a3mega_recipe="llama3.1_7b_nemo_pretraining" \
+    -var=gpu_type="A3 Mega" \
+    -var=node_count_nemo=2 \
+    -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
+    -var=a3_ultra_zone=$_A3MEGA_ZONE \
+    -var=reservation=$_A3MEGA_RESERVATION \
+    -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
+    -auto-approve -no-color
+  allowFailure: true
+  waitFor: ['check a3m nemo result']
 
 - id: 'check result'
   name: 'gcr.io/$PROJECT_ID/terraform'
@@ -339,40 +362,36 @@ steps:
   args:
   - '-c'
   - |
-    if [[ $(cat /workspace/a3u_nccl_result.txt) != "pass" ]]; then
-      echo "a3ultra with nccl creation failed"
+    if [[ $(cat /workspace/a3m_nccl_result.txt) != "cluster creation successfully" ]]; then
+      echo "a3mega with nccl cluster creation failed"
       exit 1
     fi
-
-    if [[ $(cat /workspace/a3u_llama7b_result.txt) != "pass" ]]; then
-      echo "a3ultra with llama7b creation failed"
-      exit 1
-    fi
-
-    if [[ $(cat /workspace/a3m_nccl_result.txt) != "pass" ]]; then
-      echo "a3mega with nccl creation failed"
-      exit 1
-    fi
-
-    if [[ $(cat /workspace/a3m_llama7b_result.txt) != "pass" ]]; then
-      echo "a3mega with llama7b creation failed"
-      exit 1
-    fi
-    
-    if [[ $(cat /workspace/a3m_nccl_result.txt) != "pass: nccl start successfully" ]]; then
+  
+    if [[ $(cat /workspace/a3m_nccl_result.txt) != "nccl start successfully" ]]; then
       echo "a3mega with nccl job start failed"
       exit 1
     fi
 
-    if [[ $(cat /workspace/a3m_nccl_result.txt) != "NCCL test log file(s) found matching pattern" ]]; then
-      echo "a3mega with nccl test failed or result file not found"
+    if [[ $(cat /workspace/a3m_nccl_result.txt) != "NCCL test log file(s) found with necessary contents" ]]; then
+      echo "a3mega with nccl test failed or result file not found or did nor find necessary contents"
       exit 1
     fi
 
-    
+    if [[ $(cat /workspace/a3m_nemo_result.txt) != "cluster creation successfully" ]]; then
+      echo "a3mega with nemo(llama 7b) cluster creation failed"
+      exit 1
+    fi
+  
+    if [[ $(cat /workspace/a3m_nemo_result.txt) != "nemo start successfully" ]]; then
+      echo "a3mega with nemo(llama 7b) job start failed"
+      exit 1
+    fi
 
-
-  waitFor: ['cleanup a3ultra with nccl', 'cleanup a3ultra with llama7b', 'cleanup a3mega with nccl', 'cleanup a3mega with llama7b']
+    if [[ $(cat /workspace/a3m_nemo_result.txt) != "Nemo result file found with necessary contents" ]]; then
+      echo "a3mega with nemo(llama 7b) test failed or result file not found or did nor find necessary contents"
+      exit 1
+    fi
+  waitFor: ['cleanup a3ultra with nccl', 'cleanup a3ultra with nemo', 'cleanup a3mega with nccl', 'cleanup a3mega with nemo']
 
 substitutions:
   _A3ULTRA_ZONE: ""
