test cloudbuild

diff --git a/cloudbuild_hcc.yaml b/cloudbuild_hcc.yaml
--- a/cloudbuild_hcc.yaml
+++ b/cloudbuild_hcc.yaml
@@ -13,13 +13,13 @@
 # limitations under the License.
 
 steps:
-# - id: "validate cluster"
-#   name: "hashicorp/terraform:latest"
-#   script: |
-#     terraform init -no-color
-#     terraform validate -no-color
-#   dir: "applications/hcc/"
-#   waitFor: ["-"]
+- id: "validate cluster"
+  name: "hashicorp/terraform:latest"
+  script: |
+    terraform init -no-color
+    terraform validate -no-color
+  dir: "applications/hcc/"
+  waitFor: ["-"]
 
 # - id: 'create a3ultra with nccl'
 #   name: 'gcr.io/$PROJECT_ID/terraform'
@@ -119,32 +119,32 @@ steps:
 #   allowFailure: true
 #   waitFor: ['create a3ultra with nemo']
 
-# - id: 'create a3mega with nccl'
-#   name: 'hashicorp/terraform:latest'
-#   entrypoint: 'sh'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
+- id: 'create a3m with nccl'
+  name: 'hashicorp/terraform:latest'
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
 
-#     cd /workspace/applications/hcc/
-#     terraform apply \
-#     -var-file=a3mega_workloads.tfvars \
-#     -var=project_id=$_A3MEGA_PROJECT \
-#     -var=a3mega_recipe="gke-nccl" \
-#     -var=gpu_type="A3 Mega" \
-#     -var=node_count_gke_nccl=2 \
-#     -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
-#     -var=a3_mega_zone=$_A3MEGA_ZONE \
-#     -var=reservation=$_A3MEGA_RESERVATION \
-#     -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
-#     -auto-approve -no-color
+    cd /workspace/applications/hcc/
+    terraform apply \
+    -var-file=a3mega_workloads.tfvars \
+    -var=project_id=$_A3MEGA_PROJECT \
+    -var=a3mega_recipe="gke-nccl" \
+    -var=gpu_type="A3 Mega" \
+    -var=node_count_gke_nccl=2 \
+    -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
+    -var=a3_mega_zone=$_A3MEGA_ZONE \
+    -var=reservation=$_A3MEGA_RESERVATION \
+    -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
+    -auto-approve -no-color
 
-#     echo "cluster creation successfully" > /workspace/a3m_nccl_result.txt
-#   allowFailure: true
-#   waitFor: ["validate cluster"]
+    echo "cluster creation successfully" > /workspace/a3m_nccl_result.txt
+  allowFailure: true
+  waitFor: ["validate cluster"]
 
-- id: 'wait for a3m nccl job to start'
+- id: 'wait for a3m nccl job to complete'
   name: 'gcr.io/cloud-builders/kubectl'
   entrypoint: 'sh'
   args:
@@ -153,35 +153,18 @@ steps:
     set -e
 
     gcloud container clusters get-credentials cloudbuild-a3m-nccl --location $_A3MEGA_REGION --project $_A3MEGA_PROJECT
-    # apt-get update
-    # apt-get install -y jq
-
-    # timeout=300  
-    # interval=20   
-    # start_time=$(date +%s)
-    # while [ $(date +%s) -lt $(($timeout + start_time)) ]; do
-    #     status=$(kubectl get job nccl-test-w-0 -n default -o json | jq -r '.status.conditions[-1].type')
-        
-    #     if [ "$status" = "Complete" ]; then
-    #       echo "nccl start successfully" > /workspace/a3m_nccl_result.txt
-    #       exit 0
-    #     fi
-    #     sleep $interval
-    # done
-    # echo "NCCL job did not complete"
-    # exit 1
     if kubectl wait --for=condition=complete=true job/nccl-test-w-0 -n default --timeout=300s; then
       echo "Job 'nccl-test-w-0' completed successfully."
-      echo "nccl start successfully" > /workspace/a3m_nccl_result.txt
+      echo "nccl job start successfully" > /workspace/a3m_nccl_result.txt
     else
       wait_exit_status=$? 
       echo "Job 'nccl-test-w-0' did not complete within 300 seconds or the job failed."
       exit 1 
     fi
   allowFailure: true
-  waitFor: ['-']
+  waitFor: ['create a3m with nccl']
 
-- id: 'check a3m NCCL result'
+- id: 'check a3m nccl result'
   name: 'gcr.io/cloud-builders/gsutil'
   entrypoint: 'sh'
   args:
@@ -195,7 +178,7 @@ steps:
     while [ $(date +%s) -lt $end_time ]; do
         (gsutil cat "$gcs_file_path" 2>/dev/null | grep -q "Avg bus bandwidth") && {
             echo "Success: Found required content in ${gcs_file_path}."
-            echo "NCCL test log file(s) found with necessary contents" > /workspace/a3m_nccl_result.txt
+            echo "nccl log found with necessary contents" > /workspace/a3m_nccl_result.txt
             exit 0
         }
         sleep $interval
@@ -203,155 +186,136 @@ steps:
     echo "Error: Timeout after ${timeout} seconds waiting for content in ${gcs_file_path}."
     exit 1
   allowFailure: true
-  waitFor: ["-"]
+  waitFor: ["wait for a3m nccl job to complete"]
 
-# - id: 'cleanup a3mega with nccl'
-#   name: 'hashicorp/terraform:latest'
-#   entrypoint: 'bash'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
+- id: 'cleanup a3mega with nccl'
+  name: 'hashicorp/terraform:latest'
+  entrypoint: 'bash'
+  args:
+  - '-c'
+  - |
+    set -e
 
-#     cd /workspace/applications/hcc/
-#     terraform destroy \
-#     -var-file=a3mega_workloads.tfvars \
-#     -var=project_id=$_A3MEGA_PROJECT \
-#     -var=a3mega_recipe="gke-nccl" \
-#     -var=gpu_type="A3 Mega" \
-#     -var=node_count_gke_nccl=2 \
-#     -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
-#     -var=a3_mega_zone=$_A3MEGA_ZONE \
-#     -var=reservation=$_A3MEGA_RESERVATION \
-#     -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
-#     -auto-approve -no-color
-#   allowFailure: true
-#   waitFor: ["check a3m NCCL result"]
+    cd /workspace/applications/hcc/
+    terraform destroy \
+    -var-file=a3mega_workloads.tfvars \
+    -var=project_id=$_A3MEGA_PROJECT \
+    -var=a3mega_recipe="gke-nccl" \
+    -var=gpu_type="A3 Mega" \
+    -var=node_count_gke_nccl=2 \
+    -var=goog_cm_deployment_name="cloudbuild-a3m-nccl" \
+    -var=a3_mega_zone=$_A3MEGA_ZONE \
+    -var=reservation=$_A3MEGA_RESERVATION \
+    -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
+    -auto-approve -no-color
+  allowFailure: true
+  waitFor: ["check a3m nccl result"]
 
-# - id: 'create a3mega with nemo'
-#   name: 'hashicorp/terraform:latest'
-#   entrypoint: 'sh'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
 
-#     cd /workspace/applications/hcc/
-#     terraform apply \
-#     -var-file=a3mega_workloads.tfvars \
-#     -var=project_id=$_A3MEGA_PROJECT \
-#     -var=a3mega_recipe="llama3.1_7b_nemo_pretraining" \
-#     -var=gpu_type="A3 Mega" \
-#     -var=node_count_nemo=2 \
-#     -var=goog_cm_deployment_name="cloudbuild-a3m-nemo" \
-#     -var=a3_ultra_zone=$_A3MEGA_ZONE \
-#     -var=reservation=$_A3MEGA_RESERVATION \
-#     -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
-#     -auto-approve -no-color
+- id: 'create a3m with nemo'
+  name: 'hashicorp/terraform:latest'
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
 
-#     echo "cluster creation successfully" > /workspace/a3m_nemo_result.txt
-#   allowFailure: true
-#   waitFor: ["cleanup a3mega with nccl"]
+    cd /workspace/applications/hcc/
+    terraform apply \
+    -var-file=a3mega_workloads.tfvars \
+    -var=project_id=$_A3MEGA_PROJECT \
+    -var=a3mega_recipe="llama3.1_7b_nemo_pretraining" \
+    -var=gpu_type="A3 Mega" \
+    -var=node_count_nemo=2 \
+    -var=goog_cm_deployment_name="cloudbuild-a3m-nemo" \
+    -var=a3_mega_zone=$_A3MEGA_ZONE \
+    -var=reservation=$_A3MEGA_RESERVATION \
+    -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
+    -auto-approve -no-color
 
-# - id: 'wait for a3m nemo job to start'
-#   name: 'gcr.io/cloud-builders/kubectl'
-#   entrypoint: 'sh'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
+    echo "cluster creation successfully" > /workspace/a3m_nemo_result.txt
+  allowFailure: true
+  waitFor: ["validate cluster"]
 
-#     apt-get update
-#     apt-get install -y jq
+- id: 'wait for a3m nemo job to complete'
+  name: 'gcr.io/cloud-builders/kubectl'
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
 
-#     gcloud container clusters get-credentials cloudbuild-a3m-nemo --location $_A3MEGA_REGION --project $_A3MEGA_PROJECT
-    
-#     # Set the _TIMEOUT and _INTERVAL
-#     _TIMEOUT=120  # 2 minutes
-#     _INTERVAL=5   # 5 seconds
+    gcloud container clusters get-credentials cloudbuild-a3m-nemo --location $_A3MEGA_REGION --project $_A3MEGA_PROJECT
+    if kubectl wait --for=condition=complete=true job/benchmark -n default --timeout=1200s; then
+      echo "Job 'benchmark' completed successfully."
+      echo "nemo job start successfully" > /workspace/a3m_nemo_result.txt
+    else
+      wait_exit_status=$? 
+      echo "Job 'benchmark' did not complete within 1200 seconds or the job failed."
+      exit 1 
+    fi
+  allowFailure: true
+  waitFor: ['create a3m with nemo']
 
-#     # Loop until the job status is 'Running' or _TIMEOUT
-#     while [ $(date +%s) -lt $(($_TIMEOUT + $(date +%s))) ]; do
-#         status=$(kubectl get job benchmark -n default -o json | jq -r '.status.conditions[-1].type')
+- id: 'check a3m nemo result'
+  name: 'gcr.io/cloud-builders/gsutil'
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
 
-#         if [[ "$status" == "Complete" ]]; then
-#           echo "nemo start successfully" > /workspace/a3m_nemo_result.txt
-#           exit 0
-#         fi
-#         sleep $_INTERVAL
-#     done
+    gcs_file_path="gs://${_A3MEGA_PROJECT}-cloudbuild-a3m-nemo-result/nemo-experiments/benchmark-*/dllogger/rank-0/dllogger.json"
+    keyword1="reduced_train_loss"
+    keyword2="validation_step_timing"
+    timeout=300  
+    interval=20  
+    end_time=$(($(date +%s) + timeout))
+    echo "Polling for GCS file(s): ${gcs_file_path}"
+    echo "Requiring keywords: '${keyword1}' AND '${keyword2}'"
+    echo "Timeout: ${timeout}s, Interval: ${interval}s."
+    while [ $(date +%s) -lt $end_time ]; do
+        echo "Checking GCS at $(date)..."
+        if gsutil cat "$gcs_file_path" 2>/dev/null | awk -v k1="$keyword1" -v k2="$keyword2" '
+            $0 ~ k1 { found_k1 = 1 }
+            $0 ~ k2 { found_k2 = 1 }
+            END { exit !(found_k1 && found_k2) }
+        '; then
+            echo "Success: Found file(s) with both required keywords."
+            echo "nccl log found with necessary contents" > /workspace/a3m_nemo_result.txt
+            exit 0 
+        else
+            echo "File(s) or required keywords not ready yet. Retrying..."
+        fi
+        sleep $interval
+    done
+    echo "Error: Timeout after ${timeout} seconds waiting for content in ${gcs_file_path}."
+    exit 1
+  allowFailure: true
+  waitFor: ["wait for a3m nemo job to complete"]
 
-#     echo "_TIMEOUT reached. Job did not start within $_TIMEOUT seconds."
-#     exit 1
-#   allowFailure: true
-#   waitFor: ['create a3mega with nemo']
+- id: 'cleanup a3mega with nemo'
+  name: 'hashicorp/terraform:latest'
+  entrypoint: 'bash'
+  args:
+  - '-c'
+  - |
+    set -e
 
-# - id: 'check a3m nemo result'
-#   name: 'gcr.io/cloud-builders/gsutil'
-#   entrypoint: 'sh'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
-
-#     # Set the _TIMEOUT and _INTERVAL
-#     _TIMEOUT=300  # 10 minutes
-#     _INTERVAL=30  # 15 seconds
-
-#     # Construct the bucket name and file pattern
-#     _BUCKET_NAME="${_A3MEGA_PROJECT}-cloudbuild-a3m-nemo-result"
-#     _FILE_PREFIX="nemo-experiments/benchmark-"
-#     _FILE_SUFFIX="/dllogger/rank-0/dllogger.json"
-#     _GCS_FILE_PATTERN="gs://${_BUCKET_NAME}/${_FILE_PREFIX}*${_FILE_SUFFIX}"
-
-#     while [ $(date +%s) -lt $(($_TIMEOUT + $(date +%s))) ]; do
-#       # List files matching the pattern
-#       file_list=$(gsutil ls "$_GCS_FILE_PATTERN" 2> /dev/null)
-#       if [ -n "$file_list" ]; then
-#         # Loop through each matching file
-#         for file in $file_list; do
-#           # Check for the required strings in the file
-#           if gsutil cat "$file" | grep -q "reduced_train_loss" && gsutil cat "$file" | grep -q "validation_step_timing"; then
-#             echo "Nemo result file found with necessary contents" > /workspace/a3m_nemo_result.txt
-#             exit 0
-#           else
-#             echo "Nemo result file found, but missing 'reduced_train_loss' or 'validation_step_timing'"
-#             exit 1
-#           fi
-#         done
-#       else
-#         echo "Waiting for Nemo result file(s) matching pattern: $_GCS_FILE_PATTERN"
-#         sleep $_INTERVAL
-#       fi
-#     done
-
-#     echo "_TIMEOUT reached. Nemo result file(s) not found or test did not complete within $_TIMEOUT seconds."
-#     exit 1
-#   allowFailure: true
-#   waitFor: ['wait for a3m nemo job to start']
-
-# - id: 'cleanup a3mega with nemo'
-#   name: 'hashicorp/terraform:latest'
-#   entrypoint: 'bash'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
-
-#     cd /workspace/applications/hcc/
-#     terraform destroy \
-#     -var-file=a3mega_workloads.tfvars \
-#     -var=project_id=$_A3MEGA_PROJECT \
-#     -var=a3mega_recipe="llama3.1_7b_nemo_pretraining" \
-#     -var=gpu_type="A3 Mega" \
-#     -var=node_count_nemo=2 \
-#     -var=goog_cm_deployment_name="cloudbuild-a3m-nemo" \
-#     -var=a3_ultra_zone=$_A3MEGA_ZONE \
-#     -var=reservation=$_A3MEGA_RESERVATION \
-#     -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
-#     -auto-approve -no-color
-#   allowFailure: true
-#   waitFor: ['check a3m nemo result']
+    cd /workspace/applications/hcc/
+    terraform destroy \
+    -var-file=a3mega_workloads.tfvars \
+    -var=project_id=$_A3MEGA_PROJECT \
+    -var=a3mega_recipe="llama3.1_7b_nemo_pretraining" \
+    -var=gpu_type="A3 Mega" \
+    -var=node_count_nemo=2 \
+    -var=goog_cm_deployment_name="cloudbuild-a3m-nemo" \
+    -var=a3_ultra_zone=$_A3MEGA_ZONE \
+    -var=reservation=$_A3MEGA_RESERVATION \
+    -var=placement_policy_name=$_A3MEGA_PLACEMENT_POLICY_NAME \
+    -auto-approve -no-color
+  allowFailure: true
+  waitFor: ['check a3m nemo result']
 
 # - id: 'check result'
 #   name: 'hashicorp/terraform:latest'
@@ -364,28 +328,28 @@ steps:
 #       exit 1
 #     fi
   
-#     if [[ $(cat /workspace/a3m_nccl_result.txt) != "nccl start successfully" ]]; then
-#       echo "a3mega with nccl job start failed"
+#     if [[ $(cat /workspace/a3m_nccl_result.txt) != "nccl job start successfully" ]]; then
+#       echo "a3mega with nccl job fail to complete"
 #       exit 1
 #     fi
 
-#     if [[ $(cat /workspace/a3m_nccl_result.txt) != "NCCL test log file(s) found with necessary contents" ]]; then
-#       echo "a3mega with nccl test failed or result file not found or did nor find necessary contents"
+#     if [[ $(cat /workspace/a3m_nccl_result.txt) != "nccl log found with necessary contents" ]]; then
+#       echo "a3mega with nccl test result file not found or did not find necessary contents"
 #       exit 1
 #     fi
 
 #     if [[ $(cat /workspace/a3m_nemo_result.txt) != "cluster creation successfully" ]]; then
-#       echo "a3mega with nemo(llama 7b) cluster creation failed"
+#       echo "a3mega with nemo cluster creation failed"
 #       exit 1
 #     fi
   
-#     if [[ $(cat /workspace/a3m_nemo_result.txt) != "nemo start successfully" ]]; then
-#       echo "a3mega with nemo(llama 7b) job start failed"
+#     if [[ $(cat /workspace/a3m_nemo_result.txt) != "nemo job start successfully" ]]; then
+#       echo "a3mega with nemo job start failed"
 #       exit 1
 #     fi
 
-#     if [[ $(cat /workspace/a3m_nemo_result.txt) != "Nemo result file found with necessary contents" ]]; then
-#       echo "a3mega with nemo(llama 7b) test failed or result file not found or did nor find necessary contents"
+#     if [[ $(cat /workspace/a3m_nemo_result.txt) != "nccl log found with necessary contents" ]]; then
+#       echo "a3mega with nemo test result file not found or did not find necessary contents"
 #       exit 1
 #     fi
 #   waitFor: ['cleanup a3mega with nccl', 'cleanup a3mega with nemo']
