test cloudbuild

diff --git a/cloudbuild_hcc.yaml b/cloudbuild_hcc.yaml
--- a/cloudbuild_hcc.yaml
+++ b/cloudbuild_hcc.yaml
@@ -176,7 +176,7 @@ steps:
 #   waitFor: ['-']
 
 - id: 'check a3m NCCL result'
-  name: 'gcr.io/cloud-builders/gsutil'
+  name: 'hashicorp/terraform:latest'
   entrypoint: 'sh'
   args:
   - '-c'
@@ -194,25 +194,20 @@ steps:
     echo "_BUCKET_NAME : '${_BUCKET_NAME}'"
     echo "_FILE_PATTERN: '${_FILE_PATTERN}'"
     echo "NCCL test log file1(s) : ${_GCS_FILE_PATH}"
-    # while [ $(date +%s) -lt $(($_TIMEOUT + $(date +%s))) ]; do
-      
-      if gsutil ls "$_GCS_FILE_PATH" > /dev/null 2>&1; then
-        echo "NCCL test log file2(s)"
-        if gsutil cat "$_GCS_FILE_PATH" | grep -q "Avg bus bandwidth"; then
-          echo "NCCL test log file(s) found with necessary contents" > /workspace/a3m_nccl_result.txt
-          exit 0
-        else
-          echo "NCCL test log file(s) found, but without 'Avg bus bandwidth'"
-          exit 1
-        fi
-      # else
-      #   echo "Waiting for NCCL test log file(s) matching pattern: $_GCS_FILE_PATH"
-      #   sleep $_INTERVAL
-
+    
+    if gsutil ls "$_GCS_FILE_PATH" > /dev/null 2>&1; then
+      echo "NCCL test log file2(s)"
+      if gsutil cat "$_GCS_FILE_PATH" | grep -q "Avg bus bandwidth"; then
+        echo "NCCL test log file(s) found with necessary contents" > /workspace/a3m_nccl_result.txt
+        exit 0
+      else
+        echo "NCCL test log file(s) found, but without 'Avg bus bandwidth'"
+        exit 1
       fi
-    # done
-    echo "_TIMEOUT reached. NCCL test log file(s) not found or test did not complete within $_TIMEOUT seconds."
-    exit 1
+    else
+      echo "_TIMEOUT reached. NCCL test log file(s) not found or test did not complete within $_TIMEOUT seconds."
+      exit 1
+    fi
   allowFailure: true
   waitFor: ["-"]
 
